version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  mongo:
    build:
      context: /mongo
      dockerfile: Dockerfile
    container_name: mongo-route
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  webhook:
    build:
      context: /webhook
      dockerfile: Dockerfile
    container_name: webhook-route
    ports:
      - "3001:3001"
    networks:
      - app-network

  telegram:
    build:
      context: /telegram
      dockerfile: Dockerfile
    container_name: telegram-route
    ports:
      - "8081:8081"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
